package dbgirls.ott.domain;

public enum Genre {
    ROMANCE, MELO, ACADEMY, OFFICE, FAMILY, HISTORICAL, COMEDY, FANTASY,
    PERIOD, GROWTH, MYSTERY, YOUTH, DAILY, COURT, DRAMA, MEDICAL, FRIENDSHIP,
    HORROR, HUMAN, THRILLER, SUSPENSE, CAMPUS, PSYCHOLOGICAL, ACTION, POLITICAL,
    CRIME, HEALING, REVENGE, BLACK_COMEDY, NOIR, PICARESQUE, SPY, HARD_BOILED, OMNIBUS,
    SUPER_HERO, ENSEMBLE_CAST
}
